export const gameStates = {
  WELCOME: 'WELCOME',
  INVITE_PENDING: 'INVITE_PENDING',
  READY_UP: 'READY_UP',
  READY: 'READY',
  STARTING: 'STARTING',
  STARTED: 'STARTED',
  GOAL: 'GOAL',
  END: 'END'
};
